services:
  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    volumes:
      - ./config/ollama:/root/.ollama
    deploy:
      resources:
        reservations:
            devices:
              - capabilities: [gpu]
    healthcheck:
      test: ollama --version || exit 1
    restart: always

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - ./config/open-webui:/app/backend/data
    ports:
      - "8080:8080"
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434
    depends_on:
      - ollama
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.open-webui.rule=Host(`open-webui.${HTTP_HOST}`)"
      - "traefik.http.services.open-webui.loadbalancer.server.port=8080"
    restart: always
