services:
  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    volumes:
      - ./config/ollama:/root/.ollama
      - ./Modelfile:/app/Modelfile
    healthcheck:
      test: ollama --version || exit 1
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - ./config/open-webui:/app/backend/data
    ports:
      - "8080:8080"
    environment:
      - OLLAMA_BASE_URLS=http://ollama:11434
      - ENV=dev
      - WEBUI_AUTH=False
    depends_on:
      - ollama
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.open-webui.rule=Host(`open-webui.${HTTP_HOST}`)"
      - "traefik.http.services.open-webui.loadbalancer.server.port=8080"
    restart: always
